Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_check_update = false
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = 'Asia/Shanghai'
  end

  config.vm.network "private_network", :type => 'dhcp'
  # config.vm.network "public_network", :type => 'dhcp', :bridge => 'en0: Wi-Fi (AirPort)'
  # config.vm.provision "shell", :path => "./scripts/main.sh"
end
