Vagrant.configure('2') do |config|
  config.vm.box = 'generic/arch'
  config.vm.box_check_update = false
  if Vagrant.has_plugin?('vagrant-timezone')
    config.timezone.value = 'Asia/Shanghai'
  end

  # config.vm.network "forwarded_port", guest: 8081, host: 8080
  # config.vm.network 'private_network', ip: '172.28.128.3'

  # config.vm.network "public_network", :bridge => 'en0: Wi-Fi (Wireless)'
  host_ip = `ifconfig en0 | grep "inet " | awk '{print $2}'`.chomp
  ip = host_ip.sub(/\.\d+$/, '.123')
  # config.vm.network "public_network", :bridge => 'en0: Wi-Fi (Wireless)', ip: ip
  config.vm.network "public_network", :bridge => 'en0: Wi-Fi', ip: ip
  # config.vm.provision 'shell', path: './scripts/main.sh'
  config.vm.synced_folder '.', '/home/vagrant/sync', type: 'virtualbox'
  config.vm.provision 'shell', inline: 'sudo sysctl -p'
  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--memory', 1024]
    # v.customize ['modifyvm', :id, '--memory', 2048]
  end
end
